config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :absences, only: [:new, :create, :edit, :update, :destroy]

  resources :services
  resources :therapists

  resources :week_availabilities do
    resources :time_blocks
  end

  resources :meetings do
    patch 'update_status', on: :member
    resources :media_meetings, only: [:new, :create]
  end


  resources :packages

  resources :media

  resources :patients, only: [:index, :show, :create, :update]

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  get '/422', to: 'errors#unprocessable'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :package
  has_and_belongs_to_many :media, join_table: 'media_meetings'

  validates :status, presence: true, inclusion: { in: ["No date set", "Pending", "Confirmed", "Cancelled", "Excused", "Done"] }
  def meeting_label
    patient = self.package.patient
    "#{patient.first_name} #{patient.last_name} - #{self.start_time.strftime("%d/%m/%Y %H:%M")} - #{self.end_time.strftime("%H:%M")}"
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  skip_after_action :verify_authorized, only: [:update_status]

  def index
    @therapist = current_user.therapist
    @meetings = policy_scope(Meeting).where.not(start_time: nil)
    @absences = policy_scope(Absence)
    @patients = policy_scope(Patient)
    @events_with_dates = @meetings.to_a + @absences.to_a
  end

  def show
    authorize @meeting
    if request.referrer&.include?(meetings_path)
      redirect_to meetings_path
    elsif request.referrer&.include?(patient_path(@meeting.package.patient))
      redirect_to patient_path(@meeting.package.patient)
    else
      redirect_to root_path
    end
  end

  def new
    @package = Package.find(params[:package_id]) if params[:package_id]
    @meeting = Meeting.new(package: @package)
    @duration = @package.service.duration_per_unit.to_i
    @final_available_slots = AvailableSlotsCalculator.new(@package.therapist, @package).call

    slot_class = Class.new do
      attr_reader :start_time

      def initialize(start_time)
        @start_time = start_time
      end
    end

    slots_array = @final_available_slots.values.flatten.map { |datetime| slot_class.new(datetime) }
    @final_available_slots_array = slots_array.group_by { |slot| slot.start_time.to_date }
    @final_slots_array = @final_available_slots_array.values.flatten

    authorize @meeting
  end

  def create
    @meeting = Meeting.new(meeting_params)
    authorize @meeting
    if @meeting.save
      redirect_to patient_path(@meeting.package.patient), notice: 'Meeting was successfully created.'
    else
      render :new
    end
  end

  def edit
    @media = Medium.where(therapist: current_user.therapist)
    @meeting = Meeting.find(params[:id]) # Chargez l'enregistrement existant
    @package = @meeting.package # Obtenez le package associé à la réunion
    @duration = @package.service.duration_per_unit.to_i
    @final_available_slots = AvailableSlotsCalculator.new(@package.therapist, @package).call

    slot_class = Class.new do
      attr_reader :start_time

      def initialize(start_time)
        @start_time = start_time
      end
    end

    slots_array = @final_available_slots.values.flatten.map { |datetime| slot_class.new(datetime) }
    @final_available_slots_array = slots_array.group_by { |slot| slot.start_time.to_date }
    @final_slots_array = @final_available_slots_array.values.flatten

    authorize @meeting
  end

  def update
    @media = Medium.where(therapist: current_user.therapist)
    @meeting = Meeting.find(params[:id])
    authorize @meeting

    if @meeting.update(meeting_params)
      if current_user.therapist
        redirect_to patient_path(@meeting.package.patient), notice: 'Meeting was successfully modified.'
      elsif current_user.patient
        redirect_to packages_path, notice: 'Meeting was successfully modified.'
      else
        redirect_to root_path
      end
    else
      render :edit
    end
  end


  def destroy
    authorize @meeting
    @meeting.destroy
    redirect_to meetings_url, notice: 'Meeting was successfully destroyed.'
  end

  def update_status
    @meeting = Meeting.find(params[:id])
    if @meeting.update(status: params[:status])
      redirect_to @meeting, notice: 'Status updated successfully.'
    else
      render :index
    end
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:start_time, :end_time, :status,
                                    :info_public, :info_private, :package_id,
                                    :therapist_id, :patient_id, medium_ids: [])
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/edit.html.erb
<div class="container" data-controller="slot-selection" data-slot-selection-duration="<%= @duration %>">

    <div class="shadow-rounded mt-5">
      <h2 class="text-center">Update the meeting</h2>

      <%= form_for @meeting do |f| %>

        <!-- HIDEN FIELD -->
        <% if @package %>
          <%= f.hidden_field :package_id, value: @package.id %>
        <% end %>
        <%= f.hidden_field :status, value: "Pending", data: { slot_selection_target: "status" } %>

        <!-- FIELD Start Time et End Time READ-ONLY -->
        <div class="row">

          <div class="d-flex align-items-center mt-3">
            <div class="form_circle_blue me-3">1</div>
            <div>
              <h3 class="form_step_line1">PICK A TIME SLOT</h3>
              <p class="form_step_line2">
                <strong><%= f.label :start_time, "Selected: ", class: 'mr-2' %></strong>
                <%= f.text_field :start_time, value: @meeting.start_time&.strftime('%-d %B %Y from %H:%M'), class: 'mr-4', data: { slot_selection_target: "startTime" }, readonly: true, style: "border: none;" %>
                <%= " - " %>
                <%= f.text_field :end_time, value: @meeting.end_time&.strftime('%H:%M'), class: 'mr-2', data: { slot_selection_target: "endTime" }, readonly: true, style: "border: none;" %>
              </p>
            </div>
          </div>

          <div class="" style="display: flex;">
            <div class="form-group mt-1 d-flex align-items-center">
            </div>
          </div>
          <!-- CALENDAR INFO -->
          <div class="mt-2" style="margin-bottom: 2em;">
            <%= week_calendar attribute: :start_time, events: @final_slots_array do |date, slots| %>
              <div class="day-events" style="height: 450px;">
                <% slots.each do |slot| %>
                  <div class="availability-card slot" data-slot-target="slot" data-time="<%= slot.start_time %>" data-action="click->slot-selection#select"
                      style="top: <%= calculate_top_position(slot) %>%;
                      height: <%= calculate_height_for_meeting(slot)%>%;
                      font-size: 0.75em;
                      padding: 0.06em; ">
                    <%= slot.start_time.strftime('%H:%M') %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>

        </div>


        <!-- FIELD INFO -->
        <div class="row">

        <% if current_user&.therapist %>
          <div class="<%= !current_user&.therapist ? '' : 'col-6' %>">
            <div class="d-flex align-items-center mt-3">
              <div class="form_circle_blue me-3">2</div>
              <div>
                <h3 class="form_step_line1">INFORMATION FOR YOUR PATIENT</h3>
                <p class="form_step_line2"> Optional</p>
              </div>
            </div>
            <div class="form-group mt-2">
              <%= f.text_area :info_public, class: 'form-control', style: 'height: 150px;' %>
            </div>
          </div>
        <% end %>

          <% if current_user&.therapist %>
            <div class="col-6">

              <div class="d-flex align-items-center mt-3">
                <div class="form_circle_blue me-3">3</div>
                <div>
                  <h3 class="form_step_line1">PERSONAL NOTE</h3>
                  <p class="form_step_line2"> Optional</p>
                </div>
              </div>

              <div class="form-group mt-2">
                <%= f.text_area :info_private, class: 'form-control', style: 'height: 150px;' %>
              </div>

            </div>
          <% end %>

        <% if current_user&.therapist %>
          <div class="row"></div>

              <div class="d-flex align-items-center mt-3">
                <div class="form_circle_blue me-3">4</div>
                <div>
                  <h3 class="form_step_line1">SHARE SOME VIDEOS</h3>
                  <p class="form_step_line2"> Optional</p>
                </div>
              </div>

              <div class="form-group mt-2">
                <%= f.label :media, "Select media for the meeting:" %>
                <ul>
                  <% @media.each do |medium| %>
                    <li>
                      <%= check_box_tag 'meeting[medium_ids][]', medium.id %>
                      <%= medium.title %>
                    </li>
                  <% end %>
                </ul>
              </div>

          </div>
        <% end %>

        <!-- Bouton Submit -->
        <div class="actions mt-3 d-flex justify-content-center">
          <%= f.submit 'Confirm', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
</div>

app/views/meetings/index.html.erb
<div class="container-with-sidebar">
  <%= render 'shared/sidebar' %>

  <div class="content-column">

    <div class="mb-5">
      <div class="row card-header-new">
        <h1> MY MEETINGS </h1>
    </div>

    <div class="shadow-rounded mb-5">
      <%= week_calendar attribute: :start_time, events: @events_with_dates do |date, events| %>
        <div class="day-events" style="height: 1000px; margin-bottom: 2em;">

          <% time_slots.each do |time_slot, index| %>
            <div class="time-slot"
                style="top: <%= calculate_top_position_for_time_slot(time_slot) %>%;
                        height: <%= calculate_height_for_time_slot %>%;">
              <%= index %>
            </div>
          <% end %>

          <% events.each do |event| %>
            <% if event.is_a?(Meeting) %>
              <div class="meeting-card"
                  style="top: <%= calculate_top_position(event) %>%;
                          height: <%= calculate_height_for_meeting(event) %>%;
                          background-color: <%= event.package.service.color %>;">
                <%= link_to event.package.patient.first_name[0] + ". " + event.package.patient.last_name, patient_path(event.package.patient) %>
                <div style="display: flex; align-items: center;">
                  <%= event.start_time.strftime('%H:%M') %> - <%= (event.start_time + event.package.service.duration_per_unit.minutes).strftime('%H:%M') %>
                  <span style="margin-left: 5px;"><%= status_update_form(event)%></span>
                </div>
              </div>
            <% elsif event.is_a?(Absence) %>
              <div class="absence-card"
                  style="top: <%= calculate_top_position(event) %>%;
                  height: <%= calculate_height_for_meeting(event) %>%;">
                <strong>Absence (<%= event.reason %>)</strong>
                <br>
                <%= event.start_time.strftime('%H:%M') %> à <%= event.end_time.strftime('%H:%M') %>
                <div>
                  <%= link_to edit_absence_path(event) do %>
                    <i class="fas fas-black fa-edit" title="Edit"></i>
                  <% end %>
                  <%= link_to absence_path(event), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                    <i class="fa-regular fa-trash-can" style="color: #000000;" title="Delete"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>



    <!-- WITHOUT PROPORTIONALITIES -->
    <!--
    <div class="shadow-rounded mb-5">
      <h3 class="text-center">My meetings</h3>
        <%= week_calendar attribute: :start_time, events: @events_with_dates do |date, events| %>
          <div class="day-events">
            <% events.each do |event| %>
              <% if event.is_a?(Meeting) %>
                <div class="absence-card" style="top: <%= (event.start_time.hour * 60) + event.start_time.min %>px; background-color: <%= event.package.service.color %>;">
                  <strong><%= event.start_time.strftime('%H:%M') %> to <%= (event.start_time + event.package.service.duration_per_unit.minutes).strftime('%H:%M') %></strong>
                  <br>
                  <%= event.package.service.name %>
                  <br>
                  <strong><%= event.package.patient.first_name + " " + event.package.patient.last_name %></strong>
                </div>
              <% elsif event.is_a?(Absence) %>
                <div class="absence-card" style="top: <%= (event.start_time.hour * 60) + event.start_time.min %>px;">
                  <strong><%= event.start_time.strftime('%H:%M') %> à <%= event.end_time.strftime('%H:%M') %></strong>
                  <br>
                  Absence (<%= event.reason %>)
                  <br>
                  <%= link_to edit_absence_path(event) do %>
                    <i class="fas fas-black fa-edit" title="Edit"></i>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
    </div>
    -->

  </div>

</div>


<!-- WITHOUT ABCENSES -->
<!--
    <%= week_calendar attribute: :start_time, events: @meetings_with_dates do |date, meetings| %>
      <div class="day-meetings">
        <% meetings.each do |meeting| %>
          <div class="meeting-card" style="top: <%= (meeting.start_time.hour * 60) + meeting.start_time.min %>px;">
            <%= meeting.start_time.strftime('%H:%M') %> - <%= (meeting.start_time + meeting.package.service.duration_per_unit.minutes).strftime('%H:%M') %>
            <br>
            <%= meeting.package.service.name %>
            <br>
            <% meeting.bookings.each do |booking| %>
              <%= booking.patient.first_name + " " + booking.patient.last_name %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
-->


<!-- UGLY STYLE -->
<!--
  <%= week_calendar attribute: :start_time, events: @meetings_with_dates do |date, meetings| %>
    <%= date.strftime('%A, %B %d') %>

    <div class="day-meetings">
      <% meetings.each do |meeting| %>
        <div class="meeting-card" style="top: <%= (meeting.start_time.hour * 60) + meeting.start_time.min %>px;">
          <%= meeting.start_time.strftime('%H:%M') %> - <%= (meeting.start_time + meeting.package.service.duration_per_unit.minutes).strftime('%H:%M') %>
          <br>
          <%= meeting.package.service.name %>
          <br>
          <% meeting.bookings.each do |booking| %>
            <%= booking.patient.first_name + " " + booking.patient.last_name %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
-->

app/views/meetings/new.html.erb
<div class="container" data-controller="slot-selection" data-slot-selection-duration="<%= @duration %>">
  <div class="row mt-5">
    <div class="p-4 shadow-rounded">
      <h2 class="text-center">Schedule a Meeting</h2>

      <%= form_for @meeting do |f| %>

        <!-- HIDEN FIELD -->
        <% if @package %>
          <%= f.hidden_field :package_id, value: @package.id %>
        <% end %>
        <%= f.hidden_field :status, value: "Pending", data: { slot_selection_target: "status" } %>

        <!-- FIELD Start Time et End Time READ-ONLY-->

        <div class="form-group col-md-5">
          <%= f.label :start_time, "Selected Start Time:" %>
          <%= f.text_field :start_time, class: 'form-control', data: { slot_selection_target: "startTime" }, readonly: true %>
        </div>
        <div class="form-group col-md-5">
          <%= f.label :end_time, "End Time:" %>
          <%= f.text_field :end_time, class: 'form-control', data: { slot_selection_target: "endTime" }, readonly: true %>
        </div>

        <!-- FIELD AVAILABILITIES SLOTS -->

        <div class="form-group">
          <%= week_calendar attribute: :start_time, events: @final_slots_array do |date, slots| %>
            <div class="day-events">
              <% slots.each do |slot| %>
                <div class="availability-cardd slot" data-slot-target="slot" data-time="<%= slot.start_time %>" data-action="click->slot-selection#select">
                  <%= slot.start_time.strftime('%H:%M') %>
                  <br>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="form-group">
          <%= f.label :info_public, "Public Information:" %>
          <%= f.text_area :info_public, class: 'form-control' %>
        </div>

        <% if current_user&.therapist %>
          <div class="form-group">
            <%= f.label :info_private, "Private Information (Visible only to therapists):" %>
            <%= f.text_area :info_private, class: 'form-control' %>
          </div>
        <% end %>

        <!-- Bouton Submit -->
        <div class="actions mt-3">
          <%= f.submit 'Schedule Meeting', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>