config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :absences, only: [:new, :create, :edit, :update, :destroy]

  resources :services
  resources :therapists

  resources :week_availabilities do
    resources :time_blocks
  end

  resources :meetings do
    patch 'update_status', on: :member
    resources :media_meetings, only: [:new, :create]
  end


  resources :packages

  resources :media

  resources :patients, only: [:index, :show, :create, :update]

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  get '/422', to: 'errors#unprocessable'
end

app/models/week_availability.rb
class WeekAvailability < ApplicationRecord
  belongs_to :therapist
  has_many :time_blocks, dependent: :destroy

  validates :valid_from, presence: true
  validates :valid_until, presence: true

  validate :no_overlapping_dates

  private

  def no_overlapping_dates
    return unless valid_from_changed? || valid_until_changed?

    overlapping_availabilities = self.therapist.week_availabilities.where.not(id: self.id)
                                                    .where("(valid_from <= ? AND valid_until >= ?) OR
                                                            (valid_from <= ? AND valid_until >= ?) OR
                                                            (valid_from >= ? AND valid_until <= ?)",
                                                            valid_from, valid_from, valid_until, valid_until, valid_from, valid_until)

    if overlapping_availabilities.exists?
        errors.add(:valid_from, "The availability overlaps with another one.")
        errors.add(:valid_until, "The availability overlaps with another one.")
    end
  end


end

app/controllers/week_availabilities_controller.rb
class WeekAvailabilitiesController < ApplicationController
  include Pundit

  before_action :authenticate_user!
  before_action :set_therapist

  def index
    @week_availabilities = policy_scope(WeekAvailability).where(therapist: current_user.therapist)
    @patients = policy_scope(Patient)
  end

  def new
    @week_availability = WeekAvailability.new
    authorize @week_availability
  end

  def show
    @week_availability = WeekAvailability.find(params[:id])
    authorize @week_availability
    redirect_to week_availabilities_path
  end

  def create
    @week_availability = WeekAvailability.new(week_availability_params)
    @week_availability.therapist = current_user.therapist
    authorize @week_availability

    if @week_availability.save
      redirect_to week_availabilities_path, notice: 'Week Availability was successfully created.'
    else
      flash[:alert] = @week_availability.errors.full_messages.join(", ")
      redirect_to week_availabilities_path
    end
  end

  def destroy
    @week_availability = WeekAvailability.find(params[:id])
    authorize @week_availability
    @week_availability.destroy
    redirect_to week_availabilities_path, notice: 'Week Availability was successfully deleted.', status: :found
  end

  def edit
    @week_availability = WeekAvailability.find(params[:id])
    authorize @week_availability
  end

  def update
    @week_availability = WeekAvailability.find(params[:id])
    authorize @week_availability

    if @week_availability.update(week_availability_params)
      redirect_to week_availabilities_path, notice: 'Week Availability was successfully updated.'
    else
      flash[:alert] = @week_availability.errors.full_messages.join(", ")
      redirect_to week_availabilities_path
    end
  end

  private

  def week_availability_params
    params.require(:week_availability).permit(:valid_from, :valid_until, :name)
  end

  def set_therapist
    @therapist = current_user.therapist
    redirect_to(root_path, alert: "You are not a therapist!") unless @therapist
  end

end

app/helpers/week_availabilities_helper.rb
# app/helpers/week_availabilities_helper.rb

module WeekAvailabilitiesHelper
  # Méthode pour afficher un tableau de cartes de time blocks
  def render_time_blocks_table(week_availability)
    content_tag(:table, class: 'table') do
      concat(content_tag(:thead) do
        concat(content_tag(:tr) do
          concat(content_tag(:th, 'Day'))
          concat(content_tag(:th, 'Start Time'))
          concat(content_tag(:th, 'End Time'))
          concat(content_tag(:th, 'Actions'))
        end)
      end)

      concat(content_tag(:tbody) do
        week_availability.time_blocks.each do |time_block|
          concat(render_time_block_row(time_block))
        end
      end)
    end
  end

  def render_time_block_row(time_block)
    content_tag(:tr) do
      concat(content_tag(:td, time_block.week_day))
      concat(content_tag(:td, time_block.start_time))
      concat(content_tag(:td, time_block.end_time))
      concat(content_tag(:td) do
        concat(link_to('Edit', edit_time_block_path(time_block), class: 'btn btn-warning btn-sm'))
        concat(link_to('Delete', time_block_path(time_block), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'))
      end)
    end
  end

  TOTAL_HOURS = 18.0

  def height_percentage(start_time, end_time)
    hours = (end_time - start_time).seconds.to_i / 3600.0
    (hours / TOTAL_HOURS) * 100
  end

  def top_position(start_time)
    start_hours_from_5_am = (start_time.seconds_since_midnight / 3600.0) - 5.0
    start_hours_from_5_am = 0 if start_hours_from_5_am < 0
    (start_hours_from_5_am / TOTAL_HOURS) * 100
  end


end

app/views/week_availabilities/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-md-6 offset-md-3">
      <div class="p-4 shadow-rounded">
        <h2 class="text-center">Edit Week Availability</h2>
        <%= form_with(model: @week_availability, local: true) do |form| %>
          <% if @week_availability.errors.any? %>
            <div class="alert alert-danger">
              <h4><%= pluralize(@week_availability.errors.count, "error") %> prohibited this week availability from being saved:</h4>
              <ul>
                <% @week_availability.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :valid_from %>
            <%= form.date_field :valid_from, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :valid_until %>
            <%= form.date_field :valid_until, class: 'form-control' %>
          </div>

          <div class="actions mt-3 d-grid gap-2 d-md-flex justify-content-md-center">
            <%= form.submit 'Update Week Availability', class: 'btn btn-primary' %>
            <%= link_to 'Cancel', week_availability_path(@week_availability), class: 'btn btn-outline-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/week_availabilities/index.html.erb
<div class="container-with-sidebar">
  <%= render 'shared/sidebar' %>

  <div class="content-column">

    <div class="mb-5">
      <div class="row card-header-new">
        <h1> MY AVAILABILITY </h1>
    </div>

    <div class="shadow-rounded mb-5">
      <div data-controller="toggle">
        <% @week_availabilities.each do |week_availability| %>
          <div class="mb-5">
            <div class="text-center">
              <%= week_availability.name.capitalize %> :
              From <strong><%= week_availability.valid_from.strftime('%A %d %B %Y') %></strong> to <strong><%= week_availability.valid_until.strftime('%A %d %B %Y') %></strong>
              <%= link_to new_week_availability_time_block_path(week_availability), class: 'float-right ml-2' do %>
                  <i class="fas fas-black fa-plus" title="Add Time Block"></i>
              <% end %>
              <%= link_to edit_week_availability_path(week_availability), class: 'float-right ml-2' do %>
                <i class="fas fas-black fa-edit" title="Edit"></i>
              <% end %>
              <%= link_to week_availability_path(week_availability), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'float-right ml-2' do %>
                <i class="fas fas-black fa-trash-alt" title="Delete"></i>
              <% end %>
              <button data-action="toggle#toggle" class="btn btn-sm float-right">
                <i class="fas fas-black fa-eye" data-toggle-icon></i>
              </button>
            </div>
            <div class="card-body" data-toggle-target="content">
              <table class="table table-transparent" style="height: 500px;">
                <thead>
                  <tr>
                    <% @days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] %>
                    <% @days.each do |day| %>
                      <th style="width: 14.28%;"><%= day %></th>
                    <% end %>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <% @days.each do |day| %>
                      <td>
                        <% time_blocks_for_day = week_availability.time_blocks.where(week_day: day.downcase) %>
                        <% time_blocks_for_day.each do |time_block| %>
                          <div class="time-block-card" style="height: <%= height_percentage(time_block.start_time, time_block.end_time) %>%; top: <%= top_position(time_block.start_time) %>%;">
                              <div class="card-body">
                                  <p>
                                      <strong><%= "#{time_block.start_time.strftime('%H:%M')} to #{time_block.end_time.strftime('%H:%M')}" %></strong>
                                      <br>
                                      <%= link_to edit_week_availability_time_block_path(week_availability, time_block) do %>
                                          <i class="fas fas-black fa-edit" title="Edit"></i>
                                      <% end %>
                                      <%= link_to week_availability_time_block_path(week_availability, time_block), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                                          <i class="fas fas-black fa-trash-alt" title="Delete"></i>
                                      <% end %>
                                  </p>
                              </div>
                          </div>
                        <% end %>
                      </td>
                    <% end %>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>


<!--NEW VERSION
<div class="container">

  <h1>My Availability</h1>

  <%= link_to 'Add Weekly Availability', new_week_availability_path, class: 'btn btn-primary mb-3' %>

  <% @week_availabilities.each do |week_availability| %>
    <div class="card my-3">
      <div class="card-header">
        Availability for the week of <%= week_availability.valid_from %> to <%= week_availability.valid_until %>
        <%= link_to 'Add Time Block', new_week_availability_time_block_path(week_availability), class: 'btn btn-secondary float-right ml-2' %>
        <%= link_to 'Edit', edit_week_availability_path(week_availability), class: 'btn btn-warning float-right ml-2' %>
        <%= link_to 'Delete', week_availability_path(week_availability), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger float-right ml-2' %>
      </div>
      <div class="card-body">
        <table class="table table-bordered">
          <thead>
            <tr>
              <% @days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] %>
              <% @days.each do |day| %>
                <th style="width: 14.28%;"><%= day %></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% @days.each do |day| %>
                <td>
                  <ul style="list-style: none; padding-left: 0;">
                    <% time_blocks = week_availability.time_blocks.where(week_day: day.downcase) %>
                    <% if time_blocks.any? %>
                      <% time_blocks.each do |time_block| %>
                        <li>
                          <%= "#{time_block.start_time.strftime('%I:%M %p')} - #{time_block.end_time.strftime('%I:%M %p')}" %>
                          <%= link_to 'Edit', edit_week_availability_time_block_path(week_availability, time_block), class: 'btn btn-warning btn-sm ml-2' %>
                          <%= link_to 'Delete', week_availability_time_block_path(week_availability, time_block), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm ml-2' %>
                        </li>
                      <% end %>
                    <% else %>
                      <li>No time blocks</li>
                    <% end %>
                  </ul>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

</div>
-->


<!--FINAL VERSION-->

app/views/week_availabilities/new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-md-6 offset-md-3">
      <div class="p-4 shadow-rounded">
        <h2 class="text-center">New Week Availability</h2>

        <%= form_for(@week_availability) do |f| %>
          <% if @week_availability.errors.any? %>
            <div class="alert alert-danger">
              <h4><%= pluralize(@week_availability.errors.count, "error") %> prohibited this week availability from being saved:</h4>
              <ul>
                <% @week_availability.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

          <div class="form-group">
            <%= f.label :valid_from %>
            <%= f.date_field :valid_from, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :valid_until %>
            <%= f.date_field :valid_until, class: 'form-control' %>
          </div>

          <div class="actions mt-3">
            <%= f.submit 'Create Week Availability', class: 'btn btn-primary' %>
            <%= link_to 'Cancel', week_availabilities_path, class: 'btn btn-outline-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>