config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :absences, only: [:new, :create, :edit, :update, :destroy]

  resources :services
  resources :therapists

  resources :week_availabilities do
    resources :time_blocks
  end

  resources :meetings do
    patch 'update_status', on: :member
    resources :media_meetings, only: [:new, :create]
  end


  resources :packages

  resources :media

  resources :patients, only: [:index, :show, :create, :update]

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  get '/422', to: 'errors#unprocessable'
end

app/views/shared/_card.html.erb
<!--

<% def render_card(week_availability, day) %>
  <% time_block = week_availability.time_blocks.find_by(week_day: day.downcase) %>
  <div class="card my-2">
    <div class="card-header">
      <%= day %>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <% if time_block %>
          <%= time_block.start_time %> - <%= time_block.end_time %>
          <%= link_to 'Edit', edit_week_availability_time_block_path(week_availability, time_block), class: 'btn btn-warning btn-sm float-right ml-2' %>
          <%= link_to 'Delete', week_availability_time_block_path(week_availability, time_block), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm float-right ml-2' %>
        <% else %>
          No time block for this day.
        <% end %>
      </li>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://i.ibb.co/bH60H1C/Untitled-design.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="shadow-md collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Services", "/services", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Therapists", "/therapists", class: "nav-link" %>
        </li>


  <div class="shadow-md collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <% if current_user.therapist.present? %>
            <%= link_to "My dashboard", "/meetings", class: "nav-link" %>
          <% end %>
        </li>
        <% unless current_user.therapist.present? %>
          <li class="nav-item">
            <%= link_to "My dashboard", "/packages", class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>


      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
  <div class="sidebar therapist-info">
    <div class="d-flex justify-content-center align-items-center">
        <% if @therapist.photo.attached? %>
            <div class="image-container-sidebar">
                <%= cl_image_tag(@therapist.photo.key, alt: "Therapist Photo", class: "my-image rounded-circle") %>
            </div>
        <% else %>
            <p>No photo</p>
        <% end %>
    </div>

    <div>
      <% if @therapist.present? %>
        <p class="text-center"> Welcome <%= @therapist.first_name %>!</p>
        <strong><p class="text-center"><%= @therapist.location_name %></p></strong>
        <p class="text-center"><%= @therapist.location_address %></p>
      <% end %>
    </div>

    <div class="mt-3">

      <%= link_to meetings_path, class: "button-19" do %>
          <i class="fas fa-calendar-week"></i> My meetings
      <% end %>

      <%= link_to week_availabilities_path, class: "button-19" do %>
          <i class="fas fa-calendar-week"></i> My working hours
      <% end %>

      <%= link_to new_absence_path, class: "button-19" do %>
          <i class="fas fa-plus"></i> New absence
      <% end %>

      <%= link_to new_medium_path, class: "button-19" do %>
          <i class="fas fa-plus"></i> New medium
      <% end %>

      <!-- OTHER LINK -->
    </div>

<div class="mt-3">
  <ul class="list-group sidebar-patient-list">
    <% @patients = Patient.order(:last_name) %>
    <% @patients.each do |patient| %>
      <% meetings = Meeting.joins(package: [:patient, :therapist]).where(packages: { patient: patient, therapist: current_user.therapist }) %>
      <% total_meetings = meetings.count %>

      <% if total_meetings > 0 %>
        <% non_no_date_set_meetings = meetings.where.not(status: "No date set").count %>

        <% ratio = total_meetings > 0 ? non_no_date_set_meetings.to_f / total_meetings : 0 %>

        <% red = (173 * (1 - ratio)).to_i %>
        <% green = (250 * (1 - ratio)) %>
        <% blue = (230 * (1 - ratio) + 128 * ratio).to_i %>

        <li class="d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto sidebar-patient-list">
            <%= link_to "#{patient.last_name.upcase} #{patient.first_name}", patient_path(patient), class: "" %>
          </div>
          <span class="badge rounded-pill" style="background-color: rgba(<%= red %>, <%= green %>, <%= blue %>, 1);"><%= non_no_date_set_meetings.to_i %> / <%= total_meetings %></span>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>
</div>

app/views/shared/_video.html.erb
<iframe width="490" height="275" src="<%= url %>" frameborder="0" allowfullscreen></iframe>