config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :absences, only: [:new, :create, :edit, :update, :destroy]

  resources :services
  resources :therapists

  resources :week_availabilities do
    resources :time_blocks
  end

  resources :meetings do
    patch 'update_status', on: :member
    resources :media_meetings, only: [:new, :create]
  end


  resources :packages

  resources :media

  resources :patients, only: [:index, :show, :create, :update]

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
  get '/422', to: 'errors#unprocessable'
end

app/views/pages/home.html.erb
<div class="wrapper-home-container">
  <div class="container">
    <div class="row">
      <div class="my-2">
      </div>
    </div>
    <%# SECTION 1: TITLE + IMAGE %>
    <div class="row">
      <%# SUBSECTION 1.1: TITLE + BUTTON %>
      <div class="col-md-7">
        <%# MAIN TITLE %>
        <div class="row">
          <p class="home-subtitle mb-1">CERTIFIED PROFESSIONALS</p>
          <h1>Search and find a therapist near by you</h1>
        </div>
        <%# SMALL SERIVICE CARDS %>
        <div class="row mt-4 mb-4">
          <div class="col-md-6 mt-2">
            <div class="home-card-small">
              <i class="fa-regular fa-envelope" style="color: #0052e0;"></i>
              <div style="margin-left: 1.5rem;">
                <h6>Get free consultation</h6>
                <p>Consult our professionals for free</p>
              </div>
            </div>
            <div class="home-card-small">
              <i class="fa-regular fa-handshake" style="color: #0052e0;"></i>
              <div style="margin-left: 1.5rem;">
                <h6>Free partnership</h6>
                <p>Register and explore for free</p>
              </div>
            </div>
          </div>
          <div class="col-md-6 mt-2">
            <div class="home-card-small">
              <i class="fa-solid fa-magnifying-glass" style="color: #0052e0;"></i>
              <div style="margin-left: 1.5rem;">
                <h6>Find the best therapists</h6>
                <p>Highly qualified and selected professionals</p>
              </div>
            </div>
            <div class="home-card-small">
              <i class="fa-regular fa-comments" style="color: #0052e0;"></i>
              <div style="margin-left: 1.5rem;">
                <h6>Ask your questions</h6>
                <p>Contact us for any questions</p>
              </div>
            </div>
          </div>
        </div>
        <%# ACTION BUTTON %>
        <%= link_to "See our services →", services_path, class: "button-18" %>

        <%= link_to "See our therapists →", therapists_path, class: "button-18" %>
      </div>
      <%# SUBSECTION 1.2: IMAGE %>
      <div class="col-md-5">
        <img style="max-height: 340px;" class="img-max img-fluid img-two-corners" src="https://images.unsplash.com/photo-1519824145371-296894a0daa9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80" alt="physioterapy move">
      </div>
    </div>

    <div class="row">
      <div class="my-3">
      </div>
    </div>

    <%# SECTION 2: SERVICES ICONS %>
    <div class="row">
      <p class="home-subtitle text-center mt-5">FASTEST SOLUTION</p>
      <h2 class="text-center">A full list of services at your disposal</h2>
      <div class="container mt-5 pt-3 mb-5 row">
        <div class="home-card-big col">
          <i class="fa-solid fa-bone home-icon" style="color: #0052e0;"></i>
          <h5 class="py-2 text-center">Physioterapy</h5>
          <p class="text-center">Expert care to heal, strengthen, and restore your body's mobility and
          functionality with personalized physiotherapy</p>
        </div>
        <div class="home-card-big col">
          <i class="fa-solid fa-hand home-icon" style="color: #0052e0;"></i>
          <h5 class="py-2 text-center">Osteopathy</h5>
          <p class="text-center">Holistic hands-on therapy that focuses on optimizing your body's
          natural balance and relieving pain through osteopathic techniques</p>
        </div>
        <div class="home-card-big col">
          <i class="fa-solid fa-spa home-icon" style="color: #0052e0;"></i>
          <h5 class="py-2 text-center">Massage</h5>
          <p class="text-center">Relax, rejuvenate, and release tension with skilled massage therapies
          designed to promote well-being and alleviate stress</p>
        </div>
        <div class="home-card-big col">
          <i class="fa-solid fa-dumbbell home-icon" style="color: #0052e0;"></i>
          <h5 class="py-2 text-center">Personal training</h5>
          <p class="text-center">Achieve your fitness goals with tailored personal training programs,
          guided by experienced professionals, and transform your health journey</p>
        </div>
      </div>
    </div>
  </div>
</div>